### PR TITLE
Simple multithreaded program to match two images

### PR DESCRIPTION
**Pull request by baitisj**
A simple program that uses pthreads to load and calculate sift features on two images simultaneously and then output the number of matching features between them.

### CODE REVIEW

**Comment by robwhess** [comment]
Read but haven't run yet. Looks mostly good on first glance. Could you make the number of threads configurable (e.g. via command line) instead of always using 2?

**Comment by baitisj** [comment]
Sure. Are you proposing that the program match multiple images supplied on the command line?

**Comment by robwhess** [comment]
Oh, woops. I misunderstood what was happening there. I went back and read your code more thoroughly, and yes, always exactly 2 threads makes sense. The PR looks good :+1:

**Comment by robwhess** [comment]
@baitisj thanks for the multithreaded matcher!

**Pull request merged**
